"""The four questions a reader actually has, answered from the structured output.

DeckScope's report used to open with a verdict and a weighted score:

    | Verdict        | LEAN NO    |
    | Weighted score | 45.7 / 100 |

That is an oracle's answer, and it sat at the top of a tool whose entire
architecture exists to avoid being an oracle. The agents are isolated so no
single model's opinion propagates unchecked; the opportunity module refuses to
forecast returns on principle; calibration is scored as a first-class dimension.
Then the first thing a reader saw was a judgement and a number to three
significant figures. The machinery argued "don't let eloquence outrun evidence"
and the cover page did exactly that with its own output.

This module replaces that with the four questions a reader is really asking:

    1. What did the deck claim that the evidence does not support?
    2. What did the deck leave out?
    3. What cannot be established either way yet?
    4. What should I go and find out next?

**Everything here is composed in Python from fields that already exist.** No
model is asked to write the headline. That is the same rule the evaluation
scorer follows, and for the same reason: a summary generated by a model can
overclaim, and a summary computed from counts cannot. If the arithmetic says two
claims are contested, the sentence says two.

The distinction this module introduces
--------------------------------------

The claim audit lumps together two things a reader must not confuse:

* **Contested** — the deck says X, retrieved evidence says otherwise, and the
  evidence is real. This is a *finding*. It has a source you can open.
* **Unverified** — nothing found either way. This is a *question*, not a strike
  against the company. Treating it as a strike is how an analysis quietly
  converts its own ignorance into a negative signal.

Rendering both as rows in one table let the second masquerade as the first. A
deck with six unverifiable claims and no contradictions looked much like a deck
with six contradictions, when they call for opposite responses: go do more
research, versus go ask the founder about a specific discrepancy.
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

#: Assessments that mean the evidence pushed back on the claim.
CONTESTED = ("contradicted", "partially-supported", "overstated")
#: Assessments that mean nothing was found either way.
UNVERIFIED = ("unverifiable", "unverified", "unknown", "no-evidence")
#: Assessments that mean the claim survived.
HOLDS = ("supported", "verified", "confirmed")

#: How much weight a piece of evidence carries. A contradiction resting on
#: nothing is not a contradiction; it is a disagreement between a deck and a
#: model's prior, which is not a finding DeckScope is entitled to report.
EVIDENCE_RANK = {"strong": 3, "moderate": 2, "weak": 1, "none": 0, "": 0}

SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2, "": 3}


@dataclass
class Finding:
    """One thing a reader should know, with the provenance to check it."""

    #: "contested" | "omission" | "unverified"
    kind: str
    #: The claim, or the thing the deck never mentioned.
    text: str
    #: Why it matters — the model's `so_what`, or the gap itself.
    why: str = ""
    #: How far the claim sits from the evidence.
    delta: str = ""
    severity: str = "medium"
    evidence_quality: str = ""
    source_ids: List[str] = field(default_factory=list)
    claim_id: str = ""
    #: The audit's verdict verbatim ("contradicted" vs "partially-supported").
    #: Kept because the headline must not call a partial disagreement an
    #: outright contradiction — a live run opened with "Four claims are
    #: contradicted by cited evidence" when three of the four were only
    #: partly supported, an overstatement in the most-read sentence of a
    #: report built to avoid exactly that.
    assessment: str = ""

    @property
    def is_citable(self) -> bool:
        """Whether this finding rests on evidence a reader can open."""
        return bool(self.source_ids)

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["is_citable"] = self.is_citable
        return d


@dataclass
class Findings:
    """The consolidated answer, and the counts the headline was built from."""

    headline: str = ""
    #: The deck said it; the evidence disagrees.
    contested: List[Finding] = field(default_factory=list)
    #: The evidence shows it; the deck never mentions it.
    omissions: List[Finding] = field(default_factory=list)
    #: Neither confirmed nor refuted. Research tasks, not strikes.
    unverified: List[Finding] = field(default_factory=list)
    #: Claims that survived scrutiny, so the report is not only a list of faults.
    holds: List[Finding] = field(default_factory=list)
    #: What to go and do, most important first.
    next_steps: List[str] = field(default_factory=list)
    #: An honest sentence about how much evidence any of this rests on.
    evidence_state: str = ""
    #: True when there was too little evidence to support any finding at all.
    evidence_too_thin: bool = False
    #: Why, when it is. "none_retrieved" and "none_cited" are different failures
    #: and need different sentences: one means research came back empty, the
    #: other means research worked and the analysis ignored it.
    evidence_reason: str = "ok"
    counts: Dict[str, int] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "headline": self.headline,
            "contested": [f.to_dict() for f in self.contested],
            "omissions": [f.to_dict() for f in self.omissions],
            "unverified": [f.to_dict() for f in self.unverified],
            "holds": [f.to_dict() for f in self.holds],
            "next_steps": list(self.next_steps),
            "evidence_state": self.evidence_state,
            "evidence_too_thin": self.evidence_too_thin,
            "evidence_reason": self.evidence_reason,
            "counts": dict(self.counts),
        }


def _norm(value: Any) -> str:
    return str(value or "").strip().lower()


def _severity_of(assessment: str, evidence_quality: str) -> str:
    """How hard a contested claim lands, given what backs it.

    A contradiction supported by strong evidence is a high-severity finding. The
    same contradiction resting on nothing is at most a lead worth chasing — the
    report should not let a model's unsourced disagreement read like a fact.
    """
    rank = EVIDENCE_RANK.get(_norm(evidence_quality), 0)
    if assessment == "contradicted":
        return "high" if rank >= 2 else "medium" if rank == 1 else "low"
    return "medium" if rank >= 2 else "low"


def _first_sentence(text: str, limit: int = 160) -> str:
    """A clause short enough to sit inside the headline."""
    clean = " ".join(str(text or "").split())
    # Not "; ": a delta is usually written "deck says X; evidence says Y", and
    # splitting at the semicolon keeps the claim and discards the correction —
    # which is the only half worth putting in a headline.
    for stop in (". ", " — "):
        if stop in clean:
            clean = clean.split(stop)[0]
            break
    if len(clean) > limit:
        clean = clean[:limit].rsplit(" ", 1)[0] + "…"
    return clean.rstrip(" .")


def _plural(n: int, one: str, many: str) -> str:
    return one if n == 1 else many


def _count_word(n: int) -> str:
    """Lowercase — the caller capitalises the sentence, not the word."""
    return {1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
            6: "six", 7: "seven", 8: "eight", 9: "nine"}.get(n, str(n))


def collect(comparison: Dict[str, Any],
            registry: Optional[Any] = None) -> Findings:
    """Turn one lens's comparison into the four answers.

    `registry` is optional and used only to describe how much evidence the whole
    analysis rested on. Its absence weakens the evidence statement; it never
    changes a finding.
    """
    out = Findings()
    audit = comparison.get("claim_audit") or []

    for row in audit:
        if not isinstance(row, dict):
            continue
        assessment = _norm(row.get("assessment"))
        quality = _norm(row.get("evidence_quality"))
        source_ids = [str(s) for s in (row.get("source_ids") or [])]
        base = {
            "text": str(row.get("claim") or "").strip(),
            "why": str(row.get("so_what") or "").strip(),
            "delta": str(row.get("delta") or "").strip(),
            "evidence_quality": quality,
            "source_ids": source_ids,
            "claim_id": str(row.get("id") or ""),
            "assessment": assessment,
        }
        if not base["text"]:
            continue

        if assessment in CONTESTED:
            severity = _severity_of(assessment, quality)
            if not source_ids:
                # `evidence_quality` is the model's own opinion of its evidence;
                # `source_ids` is a fact we can check. When they disagree, the
                # checkable field wins. Otherwise a model could assert
                # "strong evidence", cite nothing, and have the report describe
                # its unsupported disagreement as "contradicted by sourced
                # evidence" — which is precisely the overclaim this file exists
                # to prevent.
                severity = "low"
            out.contested.append(Finding(
                kind="contested", severity=severity, **base))
        elif assessment in UNVERIFIED:
            out.unverified.append(Finding(kind="unverified", severity="low", **base))
        elif assessment in HOLDS:
            out.holds.append(Finding(kind="holds", severity="low", **base))

    alignment = comparison.get("alignment") or {}
    for blind in (alignment.get("blind_spots") or []):
        # Both shapes are accepted: the schema now asks for objects carrying
        # their own sources, but a bare string is what older output and simpler
        # models produce, and losing the finding entirely would be worse than
        # showing it unsourced — provided it is *shown* as unsourced.
        if isinstance(blind, str):
            text, why, source_ids = blind.strip(), "", []
        else:
            text = str(blind.get("what") or blind.get("text") or "").strip()
            why = str(blind.get("why_it_matters") or "").strip()
            source_ids = [str(s) for s in (blind.get("source_ids") or [])]
        if not text:
            continue
        out.omissions.append(Finding(
            kind="omission", text=text,
            why=why or "The deck does not mention this.",
            source_ids=source_ids,
            # An omission is only "high" when evidence establishes it matters.
            # Promoting an unsourced assertion to a headline finding is how the
            # most prominent line in the report became the least checkable one.
            severity="high" if source_ids else "low"))

    # Highest-severity first, and within a severity, best-evidenced first. A
    # reader who stops after two lines should have read the two that matter.
    out.contested.sort(key=lambda f: (SEVERITY_ORDER.get(f.severity, 3),
                                      -EVIDENCE_RANK.get(f.evidence_quality, 0)))

    out.next_steps = _next_steps(comparison, out)
    out.counts = {
        "contested": len(out.contested),
        "omissions": len(out.omissions),
        "unverified": len(out.unverified),
        "holds": len(out.holds),
        "claims_examined": len(audit),
        "contested_with_evidence": sum(1 for f in out.contested if f.is_citable),
    }
    (out.evidence_state, out.evidence_too_thin,
     out.evidence_reason) = _evidence_state(out, registry)
    out.headline = compose_headline(out, comparison)
    return out


def _next_steps(comparison: Dict[str, Any], found: Findings) -> List[str]:
    """What to do next, most consequential first.

    P0 actions come before questions because an action names an owner. Anything
    unverifiable is a research task by definition, so it lands here rather than
    being reported as a mark against the company.
    """
    steps: List[str] = []
    for action in (comparison.get("actions") or []):
        if not isinstance(action, dict):
            continue
        text = str(action.get("action") or "").strip()
        if not text:
            continue
        priority = _norm(action.get("priority")) or "p2"
        steps.append((priority, text))
    steps.sort(key=lambda pair: pair[0])
    ordered = [text for _, text in steps]

    for question in (comparison.get("questions") or []):
        text = str(question or "").strip()
        if text and text not in ordered:
            # Questions are for the founder meeting; without the prefix they
            # rendered as numbered to-dos indistinguishable from diligence
            # actions (seen in a live run's 18-item list).
            ordered.append(f"Ask the founder: {text}")

    # A live self-driven run produced an 18-item wall here: five actions,
    # five founder questions, then EVERY unverified claim restated as its own
    # "Verify or refute" step — duplicating the "What could not be checked"
    # section printed two screens up. Three or more unverified claims now
    # collapse into one step that points at that section; the per-claim
    # sentence survives for the short case, where it genuinely helps.
    if len(found.unverified) >= 3:
        ordered.append(
            f"Verify or refute the {len(found.unverified)} claims listed "
            f"under \u201cWhat could not be checked\u201d — the research found "
            f"nothing either way on any of them.")
        return ordered
    for finding in found.unverified:
        # The claim goes in quotes because it is a claim, not this sentence's
        # own grammar. The old template read "Establish The financial
        # reconciliation software market is $88B — nothing found either way",
        # which is the kind of sentence that makes a reader stop trusting the
        # careful ones around it.
        claim = finding.text.strip().rstrip(".")
        if len(claim) > 90:
            claim = claim[:90].rstrip() + "…"
        ask = f"Verify or refute “{claim}” — the research found nothing either way."
        if ask not in ordered:
            ordered.append(ask)
    return ordered


def _evidence_state(found: Findings, registry: Optional[Any]) -> tuple:
    """One honest sentence about what all of this rests on.

    When research returned nothing, every "finding" is really a model's opinion
    about a deck. Saying so at the top is the difference between a report that
    is thin and a report that hides being thin.
    """
    total = cited = 0
    if registry is not None:
        try:
            stats = registry.stats()
            total = int(stats.get("total") or 0)
            cited = int(stats.get("cited") or 0)
        except Exception:  # noqa: BLE001
            total = cited = 0

    grounded = found.counts.get("contested_with_evidence", 0)
    if total == 0:
        # The headline above this line already says nothing was tested (it
        # leads with the caveat unconditionally). Repeating the same sentence
        # in italics directly underneath — which a live self-driven run showed
        # this doing — teaches the reader to skim the report's two most
        # important lines. Say the thing the headline does not: what to do.
        return ("To test these claims against real sources, configure a "
                "research backend (`deckscope setup`) and re-run.",
                True, "none_retrieved")
    if grounded == 0 and found.contested:
        return (f"{total} source(s) were retrieved, but none of the contested points "
                f"below cites one. They are readings of the deck, not findings "
                f"against evidence.", True, "none_cited")
    return (f"{grounded} of {len(found.contested)} contested "
            f"{_plural(len(found.contested), 'point cites', 'points cite')} "
            f"retrieved evidence; {cited} of {total} sources were used.",
            False, "ok")


def compose_headline(found: Findings, comparison: Dict[str, Any]) -> str:
    """The one sentence, assembled from counts rather than written by a model.

    Deliberately not a verdict. "LEAN NO" tells a reader what to think;
    "two load-bearing claims are contested and the competitive set omits the
    incumbent" tells them what to go and look at, which is the only thing this
    tool is actually in a position to say.
    """
    grounded = [f for f in found.contested if f.is_citable]
    parts: List[str] = []

    # Thin evidence outranks everything else in the sentence. An earlier version
    # only applied this when there were no omissions, which meant a run that
    # retrieved zero sources still opened with "Four claims are contested by the
    # evidence" — asserting against evidence that did not exist, in the headline
    # written to stop exactly that. The caveat now leads unconditionally, and
    # what follows is phrased as reading rather than finding.
    if found.evidence_too_thin:
        observed: List[str] = []
        if found.contested:
            n = len(found.contested)
            observed.append(f"{_count_word(n)} {_plural(n, 'claim reads', 'claims read')} "
                            f"as overstated against the deck's own internals")
        if found.omissions:
            n = len(found.omissions)
            observed.append(f"{_count_word(n)} apparent "
                            f"{_plural(n, 'gap stands', 'gaps stand')} out")
        # Two different failures need two different sentences. Announcing "no
        # external evidence was retrieved" when three sources came back and were
        # simply never cited is itself a false statement, in the very line that
        # exists to stop the report making false statements.
        if found.evidence_reason == "none_cited":
            lead = ("Evidence was retrieved, but none of the points below cites "
                    "any of it, so nothing here has been tested against a source.")
        else:
            lead = ("No external evidence was retrieved, so nothing here was "
                    "tested against anything outside the deck.")
        if not observed:
            return f"{lead} This report contains questions, not findings."
        joined = _join(observed)
        return (f"{lead} " + joined[0].upper() + joined[1:]
                + " — treat all of it as questions to investigate, not findings.")

    if grounded:
        n = len(grounded)
        # The verb must match the verdicts. "Contradicted" for a set that is
        # mostly partially-supported overstates — in the one sentence every
        # reader reads.
        outright = [f for f in grounded if f.assessment == "contradicted"]
        if len(outright) == n:
            verb = "contradicted by cited evidence"
        elif not outright:
            verb = "only partly supported by cited evidence"
        else:
            verb = (f"contested by cited evidence "
                    f"({_count_word(len(outright))} outright, "
                    f"{_count_word(n - len(outright))} partly supported)")
        # `delta` says how far the claim sits from the data, which is the most
        # specific thing available. `so_what` is often generic encouragement.
        # Lead with an outright contradiction when one exists.
        first = (outright or grounded)[0]
        lead = _first_sentence(first.delta or first.why, 120)
        parts.append(
            f"{_count_word(n)} {_plural(n, 'claim is', 'claims are')} {verb}"
            + (f" — {lead}" if lead else ""))

    if found.omissions:
        n = len(found.omissions)
        first = _first_sentence(found.omissions[0].text, 110)
        parts.append(f"the deck omits {first}"
                     + (f" and {n - 1} other {_plural(n - 1, 'gap', 'gaps')}"
                        if n > 1 else ""))

    if found.unverified:
        n = len(found.unverified)
        if parts:
            parts.append(f"{_count_word(n)} further "
                         f"{_plural(n, 'claim', 'claims')} could not be checked "
                         f"either way")
        else:
            # The only thing to report is that nothing could be established.
            # That is a statement about the evidence, not about the company.
            examined = found.counts.get("claims_examined", n)
            parts.append(f"none of the deck's {examined} examined claims could be "
                         f"confirmed or refuted with the evidence retrieved")

    if not parts:
        holds = found.counts.get("holds", 0)
        if holds:
            return (f"Nothing in this deck was contradicted by the evidence "
                    f"retrieved: {holds} of "
                    f"{found.counts.get('claims_examined', holds)} claims examined "
                    f"held up. An absence of contradictions is not proof — read "
                    f"the open questions before concluding the deck is sound.")
        return ("No claims could be assessed against the evidence retrieved for "
                "this run.")

    sentence = _join(parts)
    if found.next_steps:
        n = len(found.next_steps)
        # The collapsed "verify N claims" step is one LINE standing for N
        # questions; the headline counts the questions, not the lines. The
        # fix that shortened the list must not also shrink the reported
        # workload (its first suite run did exactly that: "One question to
        # resolve" above six unresolved claims).
        if len(found.unverified) >= 3:
            n += len(found.unverified) - 1
        # New sentence, so the count word is capitalised here. `_count_word` is
        # lowercase because it is usually mid-clause.
        count = _count_word(min(n, 9))
        sentence += (f". {count[0].upper()}{count[1:]} "
                     f"{_plural(n, 'question', 'questions')} to resolve before this "
                     f"can be judged.")
    else:
        sentence += "."
    return sentence[0].upper() + sentence[1:]


def _join(parts: List[str]) -> str:
    """Comma-separated with a final 'and'."""
    if not parts:
        return ""
    if len(parts) == 1:
        return parts[0]
    return ", ".join(parts[:-1]) + f", and {parts[-1]}"
