"""`deckscope batch <dir>` — run every deck in a folder, then rank them.

The screening workflow: an associate has a folder of this week's inbound
decks and wants one table — who survives contact with the evidence, who
doesn't, and where each full report lives. One deck failing to parse must
not cost the other nine their run, so every deck gets its own try/except
and failures become rows in the same table rather than a dead process.

Ranking is triage, not judgment: verdict first (best call at the top,
withheld verdicts in the middle where they belong — unknown is not bad),
then fewest contested claims within the same call. The table routes
attention; the per-deck reports carry the evidence.
"""
from __future__ import annotations

import re
import time
from pathlib import Path
from typing import Any, Dict, List


def _slug(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-.")
    return s or "deck"


def verdict_rank(call: str) -> int:
    """Best call first; a withheld verdict sits in the middle — 'we could
    not check' must never outrank 'we checked and it failed'... or the
    reverse. Order of tests matters: 'NO GO' contains 'GO'."""
    c = (call or "").upper()
    if not c or c in ("—", "-") or "NO VERDICT" in c or "WITHHELD" in c:
        return 2
    if "NO GO" in c or "DECLINE" in c or "PASS" in c or c == "NO":
        return 4
    if "LEAN NO" in c:
        return 3
    if "LEAN YES" in c:
        return 1
    if "GO" in c or "YES" in c or "PROCEED" in c or "INVEST" in c:
        return 0
    return 2


def _row_from_result(result: Any, lens: str) -> Dict[str, Any]:
    from ..render.common import header_block

    comp = result.comparisons.get(lens) or {}
    h = header_block(result, lens)
    audit = [r for r in (comp.get("claim_audit") or []) if isinstance(r, dict)]

    def n(*words):
        return sum(1 for r in audit
                   if str(r.get("assessment", "")).lower() in words)

    stats = result.registry.stats() if getattr(result, "registry", None) else {}
    return {
        "company": getattr(result, "company", "") or "?",
        "verdict": h.get("verdict") or "—",
        "confidence": h.get("confidence") or "—",
        "contested": n("contradicted", "partially-supported"),
        "supported": n("supported"),
        "unverifiable": n("unverifiable"),
        "questions": len(comp.get("questions") or []),
        "sources_cited": stats.get("cited", 0),
    }


def rank_rows(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return sorted(rows, key=lambda r: (
        1 if r.get("error") else 0,             # failures last
        verdict_rank(r.get("verdict", "")),
        r.get("contested", 0),
        str(r.get("company", "")).lower(),
    ))


def render_summary(rows: List[Dict[str, Any]], folder: str) -> str:
    L: List[str] = []
    add = L.append
    ok = [r for r in rows if not r.get("error")]
    failed = [r for r in rows if r.get("error")]
    add(f"# Batch screening — {folder}")
    add("")
    add(f"*{len(ok)} deck(s) analyzed"
        + (f", {len(failed)} failed" if failed else "")
        + ". Ranked by verdict, then by fewest contested claims — a triage "
        "order, not a judgment. Each deck's full report carries the "
        "evidence behind its row.*")
    add("")
    add("| # | Company | Deck | Verdict | Conf. | Contested | Supported | "
        "Unverifiable | Questions | Report |")
    add("|---|---------|------|---------|-------|-----------|-----------|"
        "--------------|-----------|--------|")
    i = 0
    for r in ok:
        i += 1
        add(f"| {i} | {r['company']} | {r['deck']} | {r['verdict']} | "
            f"{r['confidence']} | {r['contested']} | {r['supported']} | "
            f"{r['unverifiable']} | {r['questions']} | {r['out_dir']} |")
    add("")
    if failed:
        add("## Failed")
        add("")
        for r in failed:
            add(f"- **{r['deck']}** — {r['error']}")
        add("")
    add("---")
    add("*Generated by DeckScope. AI-generated analysis, not investment "
        "advice; a row is only as good as the report behind it.*")
    return "\n".join(L)


_COLUMNS = ["company", "deck", "verdict", "confidence", "contested",
            "supported", "unverifiable", "questions", "sources_cited",
            "out_dir", "error"]


# One shared implementation for every spreadsheet writer (seventh audit);
# the name is kept because it is pinned by the sixth audit's tests.
from ..render.common import safe_cell as neutralize_cell  # noqa: E402


def write_table(rows: List[Dict[str, Any]], out_dir: Path) -> Path:
    """xlsx when openpyxl is present, CSV otherwise — the table is the
    deliverable an associate pastes into the fund's tracker."""
    try:
        import openpyxl  # noqa: F401
        from openpyxl import Workbook

        wb = Workbook()
        ws = wb.active
        ws.title = "screening"
        ws.append([c.replace("_", " ") for c in _COLUMNS])
        for r in rows:
            ws.append([neutralize_cell(r.get(c, ""))
                       for c in _COLUMNS])
        p = out_dir / "summary.xlsx"
        wb.save(p)
        return p
    except ImportError:
        import csv

        p = out_dir / "summary.csv"
        with open(p, "w", newline="", encoding="utf-8") as fh:
            w = csv.DictWriter(fh, fieldnames=_COLUMNS, extrasaction="ignore")
            w.writeheader()
            for r in rows:
                w.writerow({k: neutralize_cell(v) for k, v in r.items()})
        return p


def command(args: Any) -> int:
    import sys

    from ..console import out as _out

    def _err(msg):
        _out(msg, file=sys.stderr)
    from ..config import load_config
    from ..ingest.loader import SUPPORTED_EXTENSIONS
    from ..orchestrator import Pipeline
    from ..providers.registry import get_provider
    from ..render.registry import render as render_fmt

    folder = Path(args.folder)
    if not folder.is_dir():
        _err(f"Not a folder: {folder}")
        return 2
    decks = sorted(p for p in folder.iterdir()
                   if p.is_file() and p.suffix.lower() in SUPPORTED_EXTENSIONS)
    if not decks:
        _err(f"No decks found in {folder} "
             f"(looked for {', '.join(sorted(SUPPORTED_EXTENSIONS))}).")
        return 2

    out_root = Path(getattr(args, "out", None) or "deckscope_output")
    out_root.mkdir(parents=True, exist_ok=True)
    formats = list(getattr(args, "format", None) or ["markdown"])

    cfg0 = load_config(getattr(args, "config", None))
    if getattr(args, "provider", None):
        cfg0.provider.name = args.provider

    nda = bool(getattr(args, "nda", False))
    if nda:
        # A folder of INBOUND decks is exactly where confidential material
        # lives (sixth external audit). Both providers, fail closed, before
        # a single deck is read.
        from ..tiering import is_local

        for label, pc in (("model", cfg0.provider),
                          ("extraction model", cfg0.extract_provider)):
            if pc is not None and not is_local(pc):
                _err(f"--nda refused: the configured {label} "
                     f"('{pc.name}') is not local, and batch sends every "
                     "deck in the folder to it. Use a local model or drop "
                     "--nda.")
                return 4
    provider = get_provider(cfg0.extract_provider or cfg0.provider)

    lens = (getattr(args, "lens", None) or ["investor"])
    lens = lens[0] if isinstance(lens, list) else lens

    rows: List[Dict[str, Any]] = []
    _out(f"Analyzing {len(decks)} deck(s) from {folder} — "
         f"one at a time, failures don't stop the batch.\n")
    for deck in decks:
        slug = _slug(deck.stem)
        deck_out = out_root / slug
        started = time.time()
        try:
            cfg = load_config(getattr(args, "config", None))
            if getattr(args, "provider", None):
                cfg.provider.name = args.provider
            cfg.deck_path = str(deck)
            cfg.lenses = [lens]
            if nda:
                # Search queries are deck-derived; under NDA they stay home.
                cfg.research.name = "none"
            cfg.__post_init__()
            result = Pipeline(cfg, provider=provider).run()
            deck_out.mkdir(parents=True, exist_ok=True)
            for fmt in formats:
                render_fmt(fmt, result, deck_out, slug)
            row = _row_from_result(result, lens)
            row.update(deck=deck.name, out_dir=str(deck_out), error="")
            _out(f"  [ok]   {deck.name}: {row['verdict']} "
                 f"({row['contested']} contested) "
                 f"in {time.time() - started:.0f}s")
        except KeyboardInterrupt:
            raise
        except Exception as e:  # noqa: BLE001 — continue-on-error is the point
            row = {"company": "?", "deck": deck.name, "verdict": "",
                   "confidence": "", "contested": 0, "supported": 0,
                   "unverifiable": 0, "questions": 0, "sources_cited": 0,
                   "out_dir": "", "error": f"{type(e).__name__}: {e}"}
            _err(f"  [FAIL] {deck.name}: {row['error']}")
        rows.append(row)

    ranked = rank_rows(rows)
    md = out_root / "summary.md"
    md.write_text(render_summary(ranked, folder.name), encoding="utf-8")
    table = write_table(ranked, out_root)

    failed = sum(1 for r in rows if r.get("error"))
    _out(f"\nSummary: {md}\nTable:   {table}")
    if failed == len(rows):
        return 1
    if failed:
        _out(f"{failed} deck(s) failed — their rows say why.")
    return 0
