"""The founder's fix-it list: what a skeptical fund will find, ordered by
what it costs you.

The founder lens flipped into a deliverable: not "here is your verdict"
but "here is exactly what an investor running this same analysis will see,
worst first, with the evidence they will be holding when they see it."
Materiality is the ordering because it is the founder's triage: a fatal
finding rewrites the deck; a cosmetic one waits.

Deterministic — assembled from the audited comparison, no model call.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, List

from ..findings import collect

_MATERIALITY_RANK = {"fatal": 0, "damaging": 1, "cosmetic": 2}
_MATERIALITY_LABEL = {
    "fatal": "FIX BEFORE SENDING — the investment story does not survive this",
    "damaging": "FIX — costs credibility even where the thesis survives",
    "cosmetic": "POLISH — noticed, not decisive",
}


def build_fixit(result: Any, lens: str) -> str:
    comp = result.comparisons.get(lens) or {}
    found = collect(comp, getattr(result, "registry", None))
    company = getattr(result, "company", "") or "your company"

    L: List[str] = []
    add = L.append
    add(f"# Fix-it list — {company}")
    add("")
    add("*What a skeptical fund running independent diligence will find in "
        "this deck, worst first — with the evidence they'll be holding when "
        "they find it. Generated from the same audit an investor-side run "
        "produces.*")
    add("")
    add(f"*{found.evidence_state}*")
    add("")

    n = 0
    contested = [r for r in (comp.get("claim_audit") or [])
                 if isinstance(r, dict)
                 and str(r.get("assessment", "")).lower() in (
                     "contradicted", "partially-supported")]
    contested.sort(key=lambda r: _MATERIALITY_RANK.get(
        str(r.get("materiality", "")).lower(), 3))
    if contested:
        add("## Claims the evidence pushes back on")
        add("")
        for r in contested:
            n += 1
            label = _MATERIALITY_LABEL.get(
                str(r.get("materiality", "")).lower(),
                "REVIEW — contested, materiality ungraded")
            add(f"### {n}. {r.get('claim', '')}")
            add("")
            add(f"**{label}**")
            add("")
            if r.get("market_evidence"):
                add(f"What they'll be holding: {r['market_evidence']}")
                add("")
            if r.get("delta"):
                add(f"The gap: {r['delta']}")
                add("")
            if r.get("materiality_because"):
                add(f"Why it matters at this level: "
                    f"{r['materiality_because']}")
                add("")
            if not r.get("source_ids"):
                add("*(The investor-side analysis asserted this without a "
                    "source — expect it as a question rather than a "
                    "finding.)*")
                add("")

    omissions = [b for b in ((comp.get("alignment") or {}).get("blind_spots")
                             or []) if isinstance(b, dict)]
    if omissions:
        add("## What your deck never addresses — and diligence will")
        add("")
        for b in omissions:
            n += 1
            add(f"**{n}. Add a slide (or a line) on:** {b.get('what', '')}")
            add("")
            add(f"Because: {b.get('why_it_matters', '')}")
            add("")

    unresolved = list(found.unverified)
    if unresolved:
        add("## Questions you will be asked — preempt them")
        add("")
        add("*Independent research found nothing either way on these. "
            "Whoever answers them first controls the framing — make it "
            "you, in the deck or the appendix.*")
        add("")
        for f in unresolved:
            n += 1
            add(f"**{n}.** {f.text.strip()}")
            add("")

    if n == 0:
        add("*Nothing to fix from this run — which usually means the run "
            "had no evidence to check against. Re-run with a research "
            "backend before trusting the quiet.*")
        add("")

    add("---")
    add(f"*{n} item(s), ordered by what each costs you. Generated by "
        f"DeckScope from its own audit; no additional AI call wrote this "
        f"document.*")
    return "\n".join(L)


def render(result, out_dir: Path, base: str, **kw: Any) -> List[str]:
    # The founder lens when the run has it; otherwise every lens present —
    # the audit rows are the same either way, and a founder holding only an
    # investor-lens run still deserves the list.
    lenses = (["founder"] if "founder" in result.comparisons
              else list(result.comparisons))
    paths = []
    for lens in lenses:
        p = out_dir / f"{base}_{lens}_fixit.md"
        p.write_text(build_fixit(result, lens), encoding="utf-8")
        paths.append(str(p))
    return paths
